In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset = pd.read_csv("Airbnb_Open_Data.csv")

/tmp/ipython-input-3534378416.py:1: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset = pd.read_csv("Airbnb_Open_Data.csv")

In [3]:
dataset

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,$169,1.0,0.0,NaN,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...,NaN
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,$167,1.0,1.0,7/6/2015,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...,NaN
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,$198,3.0,0.0,NaN,NaN,5.0,1.0,342.0,NaN,NaN
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,$109,2.0,5.0,10/11/2015,0.10,3.0,1.0,386.0,NaN,NaN
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,$206,1.0,0.0,NaN,NaN,3.0,1.0,69.0,NaN,NaN

# Steps for Data Preprocessing

1. Renaming the columsn
2. Deleting redundant columns
3. dropping duplicated
4. Removing the NaN values
5. Cleaning individual columns

6. Check for some more transfomration

# 1. Renaming the columns

In [4]:
dataset.columns

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license'],
      dtype='object')

In [5]:
dataset.columns = (
    dataset.columns.str.strip()
              .str.lower()
              .str.replace(r"[ -]+", "_", regex=True)
              .str.replace(r"[^\w_]", "", regex=True)
)

In [6]:
dataset.columns

Index(['id', 'name', 'host_id', 'host_identity_verified', 'host_name',
       'neighbourhood_group', 'neighbourhood', 'lat', 'long', 'country',
       'country_code', 'instant_bookable', 'cancellation_policy', 'room_type',
       'construction_year', 'price', 'service_fee', 'minimum_nights',
       'number_of_reviews', 'last_review', 'reviews_per_month',
       'review_rate_number', 'calculated_host_listings_count',
       'availability_365', 'house_rules', 'license'],
      dtype='object')

In [7]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 26 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              102599 non-null  int64
 1   name                            102349 non-null  object
 2   host_id                         102599 non-null  int64
 3   host_identity_verified          102310 non-null  object
 4   host_name                       102193 non-null  object
 5   neighbourhood_group             102570 non-null  object
 6   neighbourhood                   102583 non-null  object
 7   lat                             102591 non-null  float64
 8   long                            102591 non-null  float64
 9   country                         102067 non-null  object
 10  country_code                    102468 non-null  object
 11  instant_bookable                102494 non-null  object
 12  cancellation_policy             102523 non-null  object
 13  room_type                       102599 non-null  object
 14  construction_year               102385 non-null  float64
 15  price                           102352 non-null  object
 16  service_fee                     102326 non-null  object
 17  minimum_nights                  102190 non-null  float64
 18  number_of_reviews               102416 non-null  float64
 19  last_review                     86706 non-null   object
 20  reviews_per_month               86720 non-null   float64
 21  review_rate_number              102273 non-null  float64
 22  calculated_host_listings_count  102280 non-null  float64
 23  availability_365                102151 non-null  float64
 24  house_rules                     50468 non-null   object
 25  license                         2 non-null       object
dtypes: float64(9), int64(2), object(15)
memory usage: 20.4+ MB

# 2. Deleting redundant columns

In [8]:
columns_to_drop = ["license", "house_rules", "calculated_host_listings_count", "reviews_per_month", "review_rate_number", "id", "availability_365", "last_review"]

In [9]:
dataset[columns_to_drop]

,license,house_rules,calculated_host_listings_count,reviews_per_month,review_rate_number,id,availability_365,last_review
0,NaN,Clean up and treat the home the way you'd like...,6.0,0.21,4.0,1001254,286.0,10/19/2021
1,NaN,Pet friendly but please confirm with me if the...,2.0,0.38,4.0,1002102,228.0,5/21/2022
2,NaN,"I encourage you to use my kitchen, cooking and...",1.0,NaN,5.0,1002403,352.0,NaN
3,NaN,NaN,1.0,4.64,4.0,1002755,322.0,7/5/2019
4,NaN,"Please no smoking in the house, porch or on th...",1.0,0.10,3.0,1003689,289.0,11/19/2018
...,...,...,...,...,...,...,...,...
102594,NaN,No Smoking No Parties or Events of any kind Pl...,1.0,NaN,3.0,6092437,227.0,NaN
102595,NaN,House rules: Guests agree to the following ter...,2.0,0.02,2.0,6092990,395.0,7/6/2015
102596,NaN,NaN,1.0,NaN,5.0,6093542,342.0,NaN
102597,NaN,NaN,1.0,0.10,3.0,6094094,386.0,10/11/2015
102598,NaN,NaN,1.0,NaN,3.0,6094647,69.0,NaN

In [10]:
dataset.drop(columns=columns_to_drop, inplace = True)

In [11]:
dataset

,name,host_id,host_identity_verified,host_name,neighbourhood_group,neighbourhood,lat,long,country,country_code,instant_bookable,cancellation_policy,room_type,construction_year,price,service_fee,minimum_nights,number_of_reviews
0,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0
1,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0
2,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,US,True,flexible,Private room,2005.0,$620,$124,3.0,0.0
3,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,True,moderate,Entire home/apt,2005.0,$368,$74,30.0,270.0
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,US,False,flexible,Private room,2003.0,$844,$169,1.0,0.0
102595,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,US,True,moderate,Private room,2016.0,$837,$167,1.0,1.0
102596,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,US,True,moderate,Private room,2009.0,$988,$198,3.0,0.0
102597,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,US,True,strict,Entire home/apt,2015.0,$546,$109,2.0,5.0
102598,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,US,False,flexible,Entire home/apt,2010.0,"$1,032",$206,1.0,0.0

# 3. Deleting duplicates

In [12]:
dataset.duplicated().sum()

np.int64(541)

In [13]:
dataset.drop_duplicates(inplace=True)

In [14]:
dataset.duplicated().sum()

np.int64(0)

# 4. Removing the NaN values

In [15]:
dataset.isnull()

,name,host_id,host_identity_verified,host_name,neighbourhood_group,neighbourhood,lat,long,country,country_code,instant_bookable,cancellation_policy,room_type,construction_year,price,service_fee,minimum_nights,number_of_reviews
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102053,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False
102054,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False
102055,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False
102056,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False
102057,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False

In [16]:
dataset.isnull().value_counts()

name   host_id  host_identity_verified  host_name  neighbourhood_group  neighbourhood  lat    long   country  country_code  instant_bookable  cancellation_policy  room_type  construction_year  price  service_fee  minimum_nights  number_of_reviews
False  False    False                   False      False                False          False  False  False    False         False             False                False      False              False  False        False           False                99342
                                                                                                     True     False         False             False                False      False              False  False        False           False                  444
                                        True       False                False          False  False  False    False         False             False                False      False              False  False        False           False                  387
                                        False      False                False          False  False  False    False         False             False                False      False              False  False        True            False                  373
                True                    False      False                False          False  False  False    False         False             False                False      False              False  False        False           False                  249
                                                                                                                                                                                                                                                          ...
True   False    False                   False      False                False          False  False  False    False         False             False                False      False              False  False        True            True                     1
                                                   True                 False          False  False  False    False         False             False                False      False              False  False        False           False                    1
                True                    False      False                False          False  False  False    False         False             False                False      True               False  False        False           False                    1
                                                                                                              True          True              False                False      False              False  False        True            False                    1
                                                   True                 False          False  False  False    False         False             False                False      True               False  False        False           False                    1
Name: count, Length: 62, dtype: int64

In [17]:
dataset.isnull().sum()

name                      250
host_id                     0
host_identity_verified    289
host_name                 404
neighbourhood_group        29
neighbourhood              16
lat                         8
long                        8
country                   532
country_code              131
instant_bookable          105
cancellation_policy        76
room_type                   0
construction_year         214
price                     247
service_fee               273
minimum_nights            400
number_of_reviews         183
dtype: int64

In [18]:
(dataset.isnull().sum()/dataset.shape[0])*100

name                      0.244959
host_id                   0.000000
host_identity_verified    0.283172
host_name                 0.395853
neighbourhood_group       0.028415
neighbourhood             0.015677
lat                       0.007839
long                      0.007839
country                   0.521272
country_code              0.128358
instant_bookable          0.102883
cancellation_policy       0.074467
room_type                 0.000000
construction_year         0.209685
price                     0.242019
service_fee               0.267495
minimum_nights            0.391934
number_of_reviews         0.179310
dtype: float64

In [19]:
dataset.dropna(inplace=True)

In [20]:
dataset.isnull().sum()

name                      0
host_id                   0
host_identity_verified    0
host_name                 0
neighbourhood_group       0
neighbourhood             0
lat                       0
long                      0
country                   0
country_code              0
instant_bookable          0
cancellation_policy       0
room_type                 0
construction_year         0
price                     0
service_fee               0
minimum_nights            0
number_of_reviews         0
dtype: int64

In [21]:
(dataset.isnull().sum()/dataset.shape[0])*100

name                      0.0
host_id                   0.0
host_identity_verified    0.0
host_name                 0.0
neighbourhood_group       0.0
neighbourhood             0.0
lat                       0.0
long                      0.0
country                   0.0
country_code              0.0
instant_bookable          0.0
cancellation_policy       0.0
room_type                 0.0
construction_year         0.0
price                     0.0
service_fee               0.0
minimum_nights            0.0
number_of_reviews         0.0
dtype: float64

# 5. Cleaning individual columns

In [22]:
dataset.columns

Index(['name', 'host_id', 'host_identity_verified', 'host_name',
       'neighbourhood_group', 'neighbourhood', 'lat', 'long', 'country',
       'country_code', 'instant_bookable', 'cancellation_policy', 'room_type',
       'construction_year', 'price', 'service_fee', 'minimum_nights',
       'number_of_reviews'],
      dtype='object')

In [25]:
dataset

,name,host_id,host_identity_verified,host_name,neighbourhood_group,neighbourhood,lat,long,country,country_code,instant_bookable,cancellation_policy,room_type,construction_year,price,service_fee,minimum_nights,number_of_reviews
0,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0
1,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0
5,Large Cozy 1 BR Apartment In Midtown East,45498551794,verified,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,True,flexible,Entire home/apt,2013.0,$577,$115,3.0,74.0
7,BlissArtsSpace!,90821839709,unconfirmed,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,False,moderate,Private room,2009.0,"$1,060",$212,45.0,49.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102029,Cozy room in a 2B with backyard access,5155155913,unconfirmed,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,False,flexible,Private room,2018.0,$822,$164,1.0,9.0
102030,An East Williamsburg Delight,71564706996,verified,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,True,moderate,Private room,2015.0,$455,$91,4.0,36.0
102031,Cozy bedroom in williamsburg,83101851929,verified,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,True,flexible,Private room,2020.0,"$1,078",$216,1.0,58.0
102032,Spacious Room w/ 2 Bed,69037598918,unconfirmed,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,False,moderate,Private room,2007.0,$103,$21,7.0,40.0
102040,"Room in Queens, NY, near LGA.",56457739998,verified,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,True,strict,Private room,2022.0,$982,$196,1.0,239.0

In [26]:
dataset['host_identity_verified'].value_counts()

host_identity_verified
unconfirmed    49707
verified       49635
Name: count, dtype: int64

In [27]:
dataset['host_identity_verified'].apply(lambda x: 1 if x == "verified" else 0)

0         0
1         1
4         1
5         1
7         0
         ..
102029    0
102030    1
102031    1
102032    0
102040    1
Name: host_identity_verified, Length: 99342, dtype: int64

In [28]:
dataset

,name,host_id,host_identity_verified,host_name,neighbourhood_group,neighbourhood,lat,long,country,country_code,instant_bookable,cancellation_policy,room_type,construction_year,price,service_fee,minimum_nights,number_of_reviews
0,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0
1,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0
5,Large Cozy 1 BR Apartment In Midtown East,45498551794,verified,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,True,flexible,Entire home/apt,2013.0,$577,$115,3.0,74.0
7,BlissArtsSpace!,90821839709,unconfirmed,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,False,moderate,Private room,2009.0,"$1,060",$212,45.0,49.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102029,Cozy room in a 2B with backyard access,5155155913,unconfirmed,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,False,flexible,Private room,2018.0,$822,$164,1.0,9.0
102030,An East Williamsburg Delight,71564706996,verified,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,True,moderate,Private room,2015.0,$455,$91,4.0,36.0
102031,Cozy bedroom in williamsburg,83101851929,verified,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,True,flexible,Private room,2020.0,"$1,078",$216,1.0,58.0
102032,Spacious Room w/ 2 Bed,69037598918,unconfirmed,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,False,moderate,Private room,2007.0,$103,$21,7.0,40.0
102040,"Room in Queens, NY, near LGA.",56457739998,verified,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,True,strict,Private room,2022.0,$982,$196,1.0,239.0

In [29]:
dataset['host_identity_verified'] = dataset['host_identity_verified'].apply(lambda x: 1 if x == "verified" else 0)

In [30]:
dataset

,name,host_id,host_identity_verified,host_name,neighbourhood_group,neighbourhood,lat,long,country,country_code,instant_bookable,cancellation_policy,room_type,construction_year,price,service_fee,minimum_nights,number_of_reviews
0,Clean & quiet apt home by the park,80014485718,0,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0
1,Skylit Midtown Castle,52335172823,1,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,1,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0
5,Large Cozy 1 BR Apartment In Midtown East,45498551794,1,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,True,flexible,Entire home/apt,2013.0,$577,$115,3.0,74.0
7,BlissArtsSpace!,90821839709,0,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,False,moderate,Private room,2009.0,"$1,060",$212,45.0,49.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102029,Cozy room in a 2B with backyard access,5155155913,0,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,False,flexible,Private room,2018.0,$822,$164,1.0,9.0
102030,An East Williamsburg Delight,71564706996,1,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,True,moderate,Private room,2015.0,$455,$91,4.0,36.0
102031,Cozy bedroom in williamsburg,83101851929,1,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,True,flexible,Private room,2020.0,"$1,078",$216,1.0,58.0
102032,Spacious Room w/ 2 Bed,69037598918,0,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,False,moderate,Private room,2007.0,$103,$21,7.0,40.0
102040,"Room in Queens, NY, near LGA.",56457739998,1,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,True,strict,Private room,2022.0,$982,$196,1.0,239.0

In [32]:
dataset['country'].value_counts()

country
United States    99342
Name: count, dtype: int64

In [35]:
dataset['host_identity_verified']

0         0
1         1
4         1
5         1
7         0
         ..
102029    0
102030    1
102031    1
102032    0
102040    1
Name: host_identity_verified, Length: 99342, dtype: int64

In [36]:
dataset

,name,host_id,host_identity_verified,host_name,neighbourhood_group,neighbourhood,lat,long,country,country_code,instant_bookable,cancellation_policy,room_type,construction_year,price,service_fee,minimum_nights,number_of_reviews
0,Clean & quiet apt home by the park,80014485718,0,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0
1,Skylit Midtown Castle,52335172823,1,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,1,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0
5,Large Cozy 1 BR Apartment In Midtown East,45498551794,1,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,True,flexible,Entire home/apt,2013.0,$577,$115,3.0,74.0
7,BlissArtsSpace!,90821839709,0,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,False,moderate,Private room,2009.0,"$1,060",$212,45.0,49.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102029,Cozy room in a 2B with backyard access,5155155913,0,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,False,flexible,Private room,2018.0,$822,$164,1.0,9.0
102030,An East Williamsburg Delight,71564706996,1,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,True,moderate,Private room,2015.0,$455,$91,4.0,36.0
102031,Cozy bedroom in williamsburg,83101851929,1,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,True,flexible,Private room,2020.0,"$1,078",$216,1.0,58.0
102032,Spacious Room w/ 2 Bed,69037598918,0,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,False,moderate,Private room,2007.0,$103,$21,7.0,40.0
102040,"Room in Queens, NY, near LGA.",56457739998,1,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,True,strict,Private room,2022.0,$982,$196,1.0,239.0

In [37]:
dataset.reset_index(inplace=True)

In [38]:
dataset

,index,name,host_id,host_identity_verified,host_name,neighbourhood_group,neighbourhood,lat,long,country,country_code,instant_bookable,cancellation_policy,room_type,construction_year,price,service_fee,minimum_nights,number_of_reviews
0,0,Clean & quiet apt home by the park,80014485718,0,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0
1,1,Skylit Midtown Castle,52335172823,1,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0
2,4,Entire Apt: Spacious Studio/Loft by central park,92037596077,1,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0
3,5,Large Cozy 1 BR Apartment In Midtown East,45498551794,1,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,True,flexible,Entire home/apt,2013.0,$577,$115,3.0,74.0
4,7,BlissArtsSpace!,90821839709,0,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,False,moderate,Private room,2009.0,"$1,060",$212,45.0,49.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99337,102029,Cozy room in a 2B with backyard access,5155155913,0,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,False,flexible,Private room,2018.0,$822,$164,1.0,9.0
99338,102030,An East Williamsburg Delight,71564706996,1,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,True,moderate,Private room,2015.0,$455,$91,4.0,36.0
99339,102031,Cozy bedroom in williamsburg,83101851929,1,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,True,flexible,Private room,2020.0,"$1,078",$216,1.0,58.0
99340,102032,Spacious Room w/ 2 Bed,69037598918,0,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,False,moderate,Private room,2007.0,$103,$21,7.0,40.0
99341,102040,"Room in Queens, NY, near LGA.",56457739998,1,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,True,strict,Private room,2022.0,$982,$196,1.0,239.0

In [39]:
dataset.columns

Index(['index', 'name', 'host_id', 'host_identity_verified', 'host_name',
       'neighbourhood_group', 'neighbourhood', 'lat', 'long', 'country',
       'country_code', 'instant_bookable', 'cancellation_policy', 'room_type',
       'construction_year', 'price', 'service_fee', 'minimum_nights',
       'number_of_reviews'],
      dtype='object')

In [40]:
dataset.drop(columns="index", inplace=True)

In [41]:
dataset

,name,host_id,host_identity_verified,host_name,neighbourhood_group,neighbourhood,lat,long,country,country_code,instant_bookable,cancellation_policy,room_type,construction_year,price,service_fee,minimum_nights,number_of_reviews
0,Clean & quiet apt home by the park,80014485718,0,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0
1,Skylit Midtown Castle,52335172823,1,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0
2,Entire Apt: Spacious Studio/Loft by central park,92037596077,1,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0
3,Large Cozy 1 BR Apartment In Midtown East,45498551794,1,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,True,flexible,Entire home/apt,2013.0,$577,$115,3.0,74.0
4,BlissArtsSpace!,90821839709,0,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,False,moderate,Private room,2009.0,"$1,060",$212,45.0,49.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99337,Cozy room in a 2B with backyard access,5155155913,0,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,False,flexible,Private room,2018.0,$822,$164,1.0,9.0
99338,An East Williamsburg Delight,71564706996,1,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,True,moderate,Private room,2015.0,$455,$91,4.0,36.0
99339,Cozy bedroom in williamsburg,83101851929,1,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,True,flexible,Private room,2020.0,"$1,078",$216,1.0,58.0
99340,Spacious Room w/ 2 Bed,69037598918,0,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,False,moderate,Private room,2007.0,$103,$21,7.0,40.0
99341,"Room in Queens, NY, near LGA.",56457739998,1,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,True,strict,Private room,2022.0,$982,$196,1.0,239.0

In [43]:
dataset['instant_bookable'] = dataset['instant_bookable'].apply(lambda x: 1 if x == 1 else 0)

In [44]:
dataset

,name,host_id,host_identity_verified,host_name,neighbourhood_group,neighbourhood,lat,long,country,country_code,instant_bookable,cancellation_policy,room_type,construction_year,price,service_fee,minimum_nights,number_of_reviews
0,Clean & quiet apt home by the park,80014485718,0,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,0,strict,Private room,2020.0,$966,$193,10.0,9.0
1,Skylit Midtown Castle,52335172823,1,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,0,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0
2,Entire Apt: Spacious Studio/Loft by central park,92037596077,1,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,0,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0
3,Large Cozy 1 BR Apartment In Midtown East,45498551794,1,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,1,flexible,Entire home/apt,2013.0,$577,$115,3.0,74.0
4,BlissArtsSpace!,90821839709,0,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,0,moderate,Private room,2009.0,"$1,060",$212,45.0,49.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99337,Cozy room in a 2B with backyard access,5155155913,0,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,0,flexible,Private room,2018.0,$822,$164,1.0,9.0
99338,An East Williamsburg Delight,71564706996,1,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,1,moderate,Private room,2015.0,$455,$91,4.0,36.0
99339,Cozy bedroom in williamsburg,83101851929,1,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,1,flexible,Private room,2020.0,"$1,078",$216,1.0,58.0
99340,Spacious Room w/ 2 Bed,69037598918,0,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,0,moderate,Private room,2007.0,$103,$21,7.0,40.0
99341,"Room in Queens, NY, near LGA.",56457739998,1,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,1,strict,Private room,2022.0,$982,$196,1.0,239.0

# 6. Check for some more transfomration

In [45]:
dataset

,name,host_id,host_identity_verified,host_name,neighbourhood_group,neighbourhood,lat,long,country,country_code,instant_bookable,cancellation_policy,room_type,construction_year,price,service_fee,minimum_nights,number_of_reviews
0,Clean & quiet apt home by the park,80014485718,0,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,0,strict,Private room,2020.0,$966,$193,10.0,9.0
1,Skylit Midtown Castle,52335172823,1,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,0,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0
2,Entire Apt: Spacious Studio/Loft by central park,92037596077,1,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,0,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0
3,Large Cozy 1 BR Apartment In Midtown East,45498551794,1,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,1,flexible,Entire home/apt,2013.0,$577,$115,3.0,74.0
4,BlissArtsSpace!,90821839709,0,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,0,moderate,Private room,2009.0,"$1,060",$212,45.0,49.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99337,Cozy room in a 2B with backyard access,5155155913,0,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,0,flexible,Private room,2018.0,$822,$164,1.0,9.0
99338,An East Williamsburg Delight,71564706996,1,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,1,moderate,Private room,2015.0,$455,$91,4.0,36.0
99339,Cozy bedroom in williamsburg,83101851929,1,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,1,flexible,Private room,2020.0,"$1,078",$216,1.0,58.0
99340,Spacious Room w/ 2 Bed,69037598918,0,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,0,moderate,Private room,2007.0,$103,$21,7.0,40.0
99341,"Room in Queens, NY, near LGA.",56457739998,1,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,1,strict,Private room,2022.0,$982,$196,1.0,239.0

In [46]:
type(dataset['price'][4])

str

In [47]:
dataset['price'].head(3)

0    $966
1    $142
2    $204
Name: price, dtype: object

In [48]:
dataset['price'] = dataset['price'].str.replace("$", "")

In [50]:
dataset['price']

0          966
1          142
2          204
3          577
4        1,060
          ...
99337      822
99338      455
99339    1,078
99340      103
99341      982
Name: price, Length: 99342, dtype: object

In [52]:
dataset['price'] = dataset['price'].str.replace(r"[ -]+", "")

In [53]:
dataset['price']

0          966
1          142
2          204
3          577
4        1,060
         ...
99337      822
99338      455
99339    1,078
99340      103
99341      982
Name: price, Length: 99342, dtype: object

In [55]:
dataset['price'] = dataset['price'].str.replace(",", "")

In [58]:
dataset['price'] = dataset['price'].str.replace(" ", "")

In [59]:
type(dataset['price'][1])

str

In [61]:
dataset['price'] = dataset['price'].astype("int")

In [62]:
type(dataset['price'][1])

numpy.int64

In [64]:
dataset['service_fee'] = dataset['service_fee'].str.replace("$", "")

In [65]:
dataset['service_fee'] = dataset['service_fee'].str.replace(",", "")

In [66]:
dataset['service_fee'] = dataset['service_fee'].str.replace(" ", "")

In [67]:
dataset['service_fee'] = dataset['service_fee'].astype("int")

In [68]:
type(dataset['service_fee'][1])

numpy.int64

# Download the cleaned dataset

In [72]:
dataset.to_csv("Cleaned_Airbnb_data.csv", index=False)

In [73]:
pd.read_csv("Cleaned_Airbnb_data.csv")

,name,host_id,host_identity_verified,host_name,neighbourhood_group,neighbourhood,lat,long,country,country_code,instant_bookable,cancellation_policy,room_type,construction_year,price,service_fee,minimum_nights,number_of_reviews
0,Clean & quiet apt home by the park,80014485718,0,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,0,strict,Private room,2020.0,966,193,10.0,9.0
1,Skylit Midtown Castle,52335172823,1,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,0,moderate,Entire home/apt,2007.0,142,28,30.0,45.0
2,Entire Apt: Spacious Studio/Loft by central park,92037596077,1,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,0,moderate,Entire home/apt,2009.0,204,41,10.0,9.0
3,Large Cozy 1 BR Apartment In Midtown East,45498551794,1,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,1,flexible,Entire home/apt,2013.0,577,115,3.0,74.0
4,BlissArtsSpace!,90821839709,0,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,0,moderate,Private room,2009.0,1060,212,45.0,49.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99337,Cozy room in a 2B with backyard access,5155155913,0,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,0,flexible,Private room,2018.0,822,164,1.0,9.0
99338,An East Williamsburg Delight,71564706996,1,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,1,moderate,Private room,2015.0,455,91,4.0,36.0
99339,Cozy bedroom in williamsburg,83101851929,1,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,1,flexible,Private room,2020.0,1078,216,1.0,58.0
99340,Spacious Room w/ 2 Bed,69037598918,0,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,0,moderate,Private room,2007.0,103,21,7.0,40.0
99341,"Room in Queens, NY, near LGA.",56457739998,1,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,1,strict,Private room,2022.0,982,196,1.0,239.0

In [74]:
dataset.to_excel("Cleaned_Airbnb_data.xlsx")